url: "https://chrisjones.dev"
name: chrisjones.dev
# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  
exclude: ['vendor']